/**
 * UI copy for quiz and shared screens — one language at a time (he | en) from page dir.
 */
const STRINGS = {
  he: {
    serverDownTitle: "השרת אינו זמין כרגע",
    serverDownBody:
      "אנחנו לא מצליחים להתחבר לשרת. ודאו שהמערכת פועלת (פורט 5500) ונסו שוב.",
    serverDownRetry: "נסו שוב",
    quizChecking: "בודקים חיבור לשרת…",
    quizTitle: "שאלון מודרך",
    quizSubtitle: "ענו בשקט ובקצב שנוח לכם — אין תשובה נכונה או לא נכונה.",
    progressLabel: "התקדמות",
    chatAriaLabel: "שיחת השאלון",
    answerLabel: "תשובה",
    placeholder: "כתבו כאן את תשובתכם…",
    send: "שליחה",
    dismiss: "סגירה",
    retry: "נסו שוב",
    errorRateLimit: "שלחת יותר מדי הודעות, נסה שוב עוד קצת",
    errorMessageTooLong: "ההודעה ארוכה מדי — עד 1000 תווים",
    errorGeneric: "משהו השתבש. נסו שוב בעוד רגע.",
    navBrand: "טראומה בישראל",
    navQuiz: "שאלון",
    navContent: "תוכן",
    navDonate: "תרומה",
    navLanguageGroup: "בחירת שפה",
    navMain: "ניווט ראשי",
    navLangHe: "עברית",
    navLangEn: "English",
    navLogin: "התחברות",
    navSignUp: "הרשמה",
    authLoginTitle: "התחברות",
    authRegisterTitle: "יצירת חשבון",
    authEmail: "אימייל",
    authPassword: "סיסמה",
    authSubmitLogin: "התחברות",
    authSubmitRegister: "הרשמה",
    authSubmittingLogin: "מתחברים…",
    authSubmittingRegister: "יוצרים חשבון…",
    authNoAccount: "אין לכם חשבון?",
    authHasAccount: "כבר יש לכם חשבון?",
    authRegisterSuccessDefault: "ההרשמה הצליחה. אנא התחברו.",
    authNetworkError: "לא ניתן להתחבר לשרת. נסו שוב.",
    authTokenMissing: "ההתחברות הצליחה אך לא התקבל טוקן מהשרת.",
    authUnexpectedError: "שגיאה לא צפויה",
    navMap: "מפה",
    navGraphs: "גרפים",
    navGraphIsrael: "7 באוקטובר",
    navGraphAddictions: "התמכרויות",
    graphIsraelTitle: "ישראל לפני ואחרי 7 באוקטובר",
    graphIsraelSubtitle: "השלכות כלכליות ונפשיות",
    graphIsraelDesc: "מלחמת ה-7 באוקטובר הותירה צלקות עמוקות על מערכת בריאות הנפש, הכלכלה ושוק העבודה בישראל. דו\"ח מבקר המדינה 2025 מצביע על כשל מערכתי חריף: כ-38% מהאוכלוסייה דיווחו על תסמינים נפשיים בינוניים עד חמורים — אך פחות מ-1% קיבלו טיפול בפועל. צפויים לפתח PTSD כ-340,000 איש, ומספר המטופלים הכולל עשוי לגדול עד 680,000. הנזק הכלכלי נמדד במאות מיליארדי דולרים שנתיים, וכולל לא רק הוצאות רפואיות אלא אובדן ימי עבודה, ירידה בפריון וייקור עלות החיים.",
    graphAddictionsTitle: "התמכרויות — נתונים ומחקר",
    graphAddictionsSubtitle: "נתונים וממצאים מחקריים",
    graphAddictionsDesc: "הקשר בין טראומה להתמכרות הוא מהממצאים המוצקים ביותר בספרות המחקרית. אנשים המתמודדים עם תסמינים פוסט-טראומטיים נוטים להשתמש בחומרים ממכרים כאמצעי לוויסות רגשי — תופעה המכונה Self-Medication Hypothesis. תסמינים כמו אימפולסיביות, מחשבות פולשניות וקושי בריכוז פוגעים בשיקול הדעת ומובילים להתנהגויות מסוכנות. הנזק אינו מצטמצם לפרט: ירידה בפריון, נהיגה תחת השפעה ועבריינות נוצרות כהשפעה חיצונית ישירה מאי-טיפול בטראומה.",
    graphReadMore: "קרא עוד",
    graphReadLess: "סגור",
    graphLoading: "טוען נתונים…",
    graphBreadcrumbHome: "ראשי",
    mapPageTitle: "מפת פניות לפי עיר ורבעון",
    mapPlay: "ניגון",
    mapPause: "השהיה",
    mapLoading: "טוען נתונים…",
    mapError: "לא ניתן לטעון את המפה",
    mapDemoHint:
      "מוצגים נתוני הדגמה — הפעילו את השרת ואת מסד הנתונים לנתונים חיים.",
    mapTimeLabel: "תקופה",
    mapCallsUnit: "פניות",
    mapGenderFemale: "נקבה",
    mapGenderMale: "זכר",
    mapGenderBoth: "הכל",
    mapGenderLabel: "מגדר",
    mapGenderAllHint: "ללא סינון מגדר (כל המגדרים)",
    mapGenderFiltersAria: "סינון לפי מגדר",
    mapAgesLabel: "גילאים",
    mapAgesAllAges: "כל הגילאים",
    mapDateStartsLabel: "התחלה",
    mapDateEndsLabel: "סיום",
  },
  en: {
    serverDownTitle: "The server is unavailable",
    serverDownBody:
      "We can't reach the learning server right now. Make sure the backend is running on port 5500, then try again.",
    serverDownRetry: "Retry",
    quizChecking: "Checking server connection…",
    quizTitle: "Guided questionnaire",
    quizSubtitle:
      "Answer gently and at your own pace — there are no wrong answers.",
    progressLabel: "Progress",
    chatAriaLabel: "Quiz conversation",
    answerLabel: "Your answer",
    placeholder: "Type your answer here…",
    send: "Send",
    dismiss: "Close",
    retry: "Retry",
    errorRateLimit: "Too many messages, please wait a little while",
    errorMessageTooLong: "Message too long — maximum 1000 characters",
    errorGeneric: "Something went wrong. Please try again.",
    navBrand: "Trauma in Israel",
    navQuiz: "Quiz",
    navContent: "Content",
    navDonate: "Donate",
    navLanguageGroup: "Choose language",
    navMain: "Main navigation",
    navLangHe: "עברית",
    navLangEn: "English",
    navLogin: "Login",
    navSignUp: "Sign up",
    authLoginTitle: "Login",
    authRegisterTitle: "Create account",
    authEmail: "Email",
    authPassword: "Password",
    authSubmitLogin: "Login",
    authSubmitRegister: "Sign up",
    authSubmittingLogin: "Signing in…",
    authSubmittingRegister: "Creating account…",
    authNoAccount: "Don't have an account?",
    authHasAccount: "Already have an account?",
    authRegisterSuccessDefault: "Registration successful. Please log in.",
    authNetworkError: "Could not reach the server. Please try again.",
    authTokenMissing:
      "Login succeeded but no token was returned by the server.",
    authUnexpectedError: "Unexpected error",
    navMap: "Map",
    navGraphs: "Graphs",
    navGraphIsrael: "Israel & the War",
    navGraphAddictions: "Addictions",
    graphIsraelTitle: "Israel Before and After Oct. 7",
    graphIsraelSubtitle: "Economic & Mental Health Impact",
    graphIsraelDesc: "The war of October 7 left deep scars on Israel's mental health system, economy, and labor market. The State Comptroller Report 2025 points to a serious systemic failure: approximately 38% of the population reported moderate to severe mental health symptoms — yet fewer than 1% received actual treatment. About 340,000 people are expected to develop PTSD, and the total number of patients may rise to 680,000. The economic damage runs into hundreds of billions annually, including not only medical expenditure but also lost workdays, declining productivity, and rising cost of living.",
    graphAddictionsTitle: "Addictions — Data & Research",
    graphAddictionsSubtitle: "Research Data & Findings",
    graphAddictionsDesc: "The link between trauma and addiction is among the most robust findings in research literature. People coping with post-traumatic symptoms tend to use addictive substances as a means of emotional regulation — a phenomenon known as the Self-Medication Hypothesis. Symptoms such as impulsivity, intrusive thoughts, and difficulty concentrating impair judgment and lead to risky behaviors. The damage extends beyond the individual: reduced productivity, drunk driving, and criminal behavior arise as direct external consequences of untreated trauma.",
    graphReadMore: "Read more",
    graphReadLess: "Close",
    graphLoading: "Loading data…",
    graphBreadcrumbHome: "Home",
    mapPageTitle: "Calls by city over time",
    mapPlay: "Play",
    mapPause: "Pause",
    mapLoading: "Loading data…",
    mapError: "Could not load map data",
    mapDemoHint:
      "Showing sample data — run the backend and database for live counts.",
    mapTimeLabel: "Period",
    mapCallsUnit: "calls",
    mapGenderFemale: "Female",
    mapGenderMale: "Male",
    mapGenderBoth: "Both",
    mapGenderLabel: "Gender",
    mapGenderAllHint: "No gender filter (all)",
    mapGenderFiltersAria: "Filter by gender",
    mapAgesLabel: "Ages",
    mapAgesAllAges: "All ages",
    mapDateStartsLabel: "Starts",
    mapDateEndsLabel: "Ends",
  },
};

export function getUiStrings(dirOrLocale) {
  if (dirOrLocale === "he" || dirOrLocale === "en") {
    return STRINGS[dirOrLocale];
  }
  return STRINGS[dirOrLocale === "rtl" ? "he" : "en"];
}
