name: Run Python Cron Job

on:
  schedule:
    - cron: '0 * * * *'   # Every 1 hours
  workflow_dispatch:      # Allows manual run from GitHub UI


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          python3 -m pip install -r server/services/googleTrends/requirements.txt

      - name: Run script
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python3 server/services/googleTrends/google_trends.py